config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get '/my_reviews/:id' => 'users#my_reviews'
  resources :books, only: [:show, :index]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
    has_many :reviews, dependent: :destroy
end

app/models/review.rb
class Review < ApplicationRecord
    belongs_to :user
    belongs_to :book
end

app/models/user.rb
class User < ApplicationRecord
    has_many :reviews, dependent: :destroy
    has_many :books
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/books_controller.rb
require 'pry'
class BooksController < ApplicationController
    def index
        @books = Book.all
    end

    def show
        @page = params[:review_page].to_i #this will be 0 if nil
        @book = Book.find(params[:id])
        @reviews = @book.reviews.limit(10).offset(@page * 10)
    end
end

app/controllers/users_controller.rb
require 'pry'

class UsersController < ApplicationController
    def my_reviews
        @user = User.find(params[:id])
        render template: "my_reviews"
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/books/index.html.erb
<% @books.each do |book| %>
    <%= book.title %>
    <%= book.author %>
<% end %>

app/views/books/show.html.erb
<%= @book.title %>
<%= @book.author %>
<% unless @book.reviews.empty? %>
    <% @reviews.each do |review| %>
        <%= review.title %>
        <%= sanitize review.content %>
        by <%= review.user.full_name %>
    <% end %>
    <%= link_to "Next page", book_path(@book, params: {review_page: @page + 1}) %>
<% else %>
    <p>This book has no reviews yet.</p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Problem3</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>